trigger:
- master

pool:
  name: default

steps:
- script: packer build config.pkr.hcl -var "vsphere_password=${env:VSPHERE_PASSWORD}"
  workingDirectory: $(Pipeline.Workspace)\s\packer\ws2016core
  displayName: 'Build the packer image'