trigger:
- master

pool:
  name: default

steps:
- script: packer build -var "vsphere_password=$(vsphere.password)" config.pkr.hcl
  workingDirectory: $(Pipeline.Workspace)\s\packer\ws2016core
  displayName: 'Build the packer image'